name: "Hello Docker"
description: 'Greet someone'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The time we greeted you'
    value: ${{ steps.say-hello.outputs.time }}
runs:
  using: composite
  steps:
      - id: say-hello
        shell: sh
        run: |
          echo "Hello ${{ inputs.who-to-greet }}!"
          time="$(date)"
          # echo "::set-output name=time::$time"
          echo "time=$time" >> "$GITHUB_OUTPUT"
      - id: dump env
        shell: sh
        run: |
          env

  

##  image: ghcr.io/willabides/actiontest:docker
#  image: Dockerfile
#  args:
#    - ${{ inputs.who-to-greet }}
#  env:
#    FOO: 'bar'
