name: 'Hello World'
description: 'Greet someone'
runs:
  using: "composite"
  steps:
    - run: echo "hello world"
      shell: sh
    - name: Dump job context
      shell: sh
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
