name: checkcheck
on: [ push, pull_request, workflow_dispatch, delete ]
jobs:
  hellodocker:
    name: hellodocker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          who-to-greet: "world"
  helloworld:
    name: helloworld
    runs-on: ubuntu-20.04
    steps:
#      - uses: actions/checkout@v2
      - uses: AWholeNewOrg/actiontest@v1.0.0
#  something-else:
#    name: something-else
#    runs-on: ubuntu-20.04
#    steps:
#      - run: echo hi
#      - name: stat
#        run: |
#          CHECK_SUITE_URL=$(curl -s -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID} | jq -r '.check_suite_url')
#          CHECK_RUN_ID=$(curl -s -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.antiope-preview+json" $CHECK_SUITE_URL/check-runs | jq '.check_runs[] | select(.name=="something-else") | .id ')
#          update='{"output": {"title": "another title","text": "foo text", "summary": "foo summary"}}'
#          curl --silent -X 'PATCH' -d "$update" \
#            -H 'Accept: application/vnd.github.v3+json' \
#            -H 'Content-Type: application/json' \
#            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
#            "https://api.github.com/repos/$GITHUB_REPOSITORY/check-runs/$CHECK_RUN_ID"
#  check-it:
#    name: check-it-name
#    runs-on: ubuntu-20.04
#    steps:
#      - name: dump env
#        run: env
#      - name: Dump GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        run: echo "$GITHUB_CONTEXT"
#      - name: Dump Job context
#        env:
#          JOB_CONTEXT: ${{ toJson(job) }}
#        run: echo "$JOB_CONTEXT"
#      - name: Dump Steps
#        env:
#          STEPS_CONTEXT: ${{ toJson(steps) }}
#        run: echo "$STEPS_CONTEXT"
#      - name: get run
#        run: |
#          curl -s \
#            -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
#            https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID} | jq .
#      - name: get jobs
#        run: |
#          curl -s \
#            -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
#            https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/jobs | jq .
#      - name: get the check run id for each job
#        run: |
#          CHECK_SUITE_URL=$(curl -s -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID} | jq -r '.check_suite_url')
#          CHECK_RUN_ID=$(curl -s -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.antiope-preview+json" $CHECK_SUITE_URL/check-runs | jq '.check_runs[] | select(.name=="prcheck") | .id ')
#          echo $CHECK_RUN_ID
#          curl -s \
#            -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
#            -H "Accept: application/vnd.github.antiope-preview+json" \
#            $CHECK_SUITE_URL/check-runs | jq .
