name: ci
on: [push, pull_request]
jobs:
  cibuild:
    if: ${{ ! ( github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork != true ) }}
    name: cibuild
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.14.0'
      - run: script/generate --check
      - run: script/test
      - run: script/lint
  howdy:
    runs-on: ubuntu-20.04
    name: "howdy"
    steps:
      - uses: WillAbides/actiontest/actions/helloworld@master
