name: ci
on: [push, pull_request]
jobs:
  old:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.15.0'
      - run: go version
  new:
    runs-on: ubuntu-20.04
    steps:
      - name: setup go
        run: |
          export GOROOT=""
          go env -w GOROOT="$GOROOT_1_15_X64"
          export PATH="$(go env GOROOT)/bin:$PATH"
          echo "PATH=$PATH" >> $GITHUB_ENV
      - name: go verion
        run: go version
