name: ci
on: [push, pull_request]
jobs:
#  cibuild:
#    if: ${{ ! ( github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork != true ) }}
#    name: cibuild
#    runs-on: ubuntu-18.04
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-go@v2
#        with:
#          go-version: '~1.14.0'
#      - run: script/generate --check
#      - run: script/test
#      - run: script/lint
  howdy:
    env:
      ACTION_REF: master
    runs-on: ubuntu-20.04
    name: "howdy"
    steps:
      - run: |
          go env -w GOROOT="$GOROOT_1_15_X64"
          which go
          go version
#          which -a go
#          go version
#          ls -al /usr/bin/go
#          ls -al /bin/go
#          env
#          go env
#          echo AGENT_TOOLSDIRECTORY=$AGENT_TOOLSDIRECTORY
#          du -h $AGENT_TOOLSDIRECTORY/go
#          ls -haltr $AGENT_TOOLSDIRECTORY/go
#      - uses: actions/checkout@v2
#      - uses: ./.github/actions/helloworld
#        with:
#          cache-prefix: mycache
