name: ci
on: [push, pull_request]
jobs:
  old:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.15'
      - run: go version
  new:
    runs-on: ubuntu-20.04
    steps:
      - name: setup go
        run: |
          echo "PATH=$GOROOT_1_15_X64/bin:$PATH" >> $GITHUB_ENV
          echo "GOROOT=$GOROOT_1_15_X64" >> $GITHUB_ENV
      - name: go verion
        run: |
          go version
          go env
