name: Docker

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: awholeneworg/actiontest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Generate Image Tags
        id: generate-image-tags
        run: |
          # Generate tags for the image
          tags=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          echo "::set-output name=tags::$tags"
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.generate-image-tags.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
