name: Reusable
on:
  workflow_call:
    inputs:
      x:
        description: manual override for x
        type: string
        required: true
#    secrets:
#      pagerduty_token:
#        required: true
jobs:
  resusable:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{inputs.x}}
